return {
  { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
  { "folke/tokyonight.nvim", enabled = false },
  { "L3MON4D3/LuaSnip" },
  { "hrsh7th/cmp-nvim-lsp" },
  { "ThePrimeagen/harpoon" },
  { "VonHeikemen/lsp-zero.nvim" },
  { "nvim-lualine/lualine.nvim" },
  { "williamboman/mason-lspconfig.nvim" },
  { "WhoIsSethDaniel/mason-tool-installer" },
  { "williamboman/mason.nvim" },
  { "echasnovski/mini.hipatterns" },
  { "folke/noice.nvim" },
  { "MunifTanjim/nui.nvim" },
  { "hrsh7th/nvim-cmp" },
  { "neovim/nvim-lspconfig" },
  { "rcarriga/nvim-notify" },
  { "nvim-tree/nvim-tree.lua" },
  { "nvim-treesitter/nvim-treesitter" },
  { "nvim-tree/nvim-web-devicons" },
  { "nvim-lua/plenary.nvim" },
  { "nvim-lua/popup.nvim" },
  { "nvim-telescope/telescope.nvim" },
  { "christoomey/vim-tmux-navigator" },
  { "tpope/vim-fugitive" },
}
